package com.game.entities.vilagers;

public enum VillagerTrades {
	
	WOOD_TO_COIN(),
	APPLE_TO_COIN(),
	COIN_TO_TACO(),
	COIN_TO_PIE(),
	COIN_TO_CHEST(),
	WOOD_TO_SIGN(),
	STONE_TO_COIN(),
	IRON_ORE_TO_COIN(),
	GOLD_ORE_TO_COIN(),
	DIAMOND_ORE_TO_COIN(),
	COIN_TO_RED_MUSHROOM(),
	COIN_TO_HEART(),
	WOOD_TO_BOWL(),
	BOWL_AND_RED_MUSHROOM_TO_MUSHROOM_STEW(),
	COIN_TO_BREAD(),
	COIN_TO_FISHING_ROD(),
	GOLD_FISH_TO_COIN(),
	BLUE_FISH_TO_COIN(),
	SALMON_FISH_TO_COIN(),
	COD_FISH_TO_COIN(),
	COIN_TO_ATTACK_STAT(),
	COIN_TO_DEFENCE_STAT();

}
